apiVersion: v1
kind: ConfigMap
metadata:
  name: aura-config
  namespace: aura-system
data:
  NODE_ENV: "production"
  PORT: "3000"
  REDIS_HOST: "aura-redis-service"
  REDIS_PORT: "6379"
  EHR_ENCRYPTION_KEY_ACTIVE: "v2"

---
apiVersion: v1
kind: Secret
metadata:
  name: aura-secrets
  namespace: aura-system
type: Opaque
stringData:
  POSTGRES_USER: "aura"
  POSTGRES_PASSWORD: "aura_k8s_prod_secure_password"
  POSTGRES_DB: "aura_prod"
  DATABASE_URL: "postgresql://aura:aura_k8s_prod_secure_password@aura-postgres-service:5432/aura_prod?schema=public"
  REDIS_PASSWORD: "aura_redis_k8s_secret"
  JWT_SECRET: "aura_jwt_master_k8s_production_key_2026"
  EHR_ENCRYPTION_KEY_V2: "0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef"
