apiVersion: v1
kind: ConfigMap
metadata:
  name: aura-config
  namespace: aura-system
data:
  NODE_ENV: "production"
  PORT: "3000"
  REDIS_HOST: "aura-redis-service"
  REDIS_PORT: "6379"
  EHR_ENCRYPTION_KEY_ACTIVE: "v2"

---
apiVersion: v1
kind: Secret
metadata:
  name: aura-secrets
  namespace: aura-system
type: Opaque
# Em produção, este secret é injetado dinamicamente via ExternalSecrets Operator / AWS Secrets Manager
stringData:
  POSTGRES_USER: "aura"
  POSTGRES_PASSWORD: "${AURA_POSTGRES_PASSWORD}"
  POSTGRES_DB: "aura_prod"
  DATABASE_URL: "${AURA_DATABASE_URL}"
  REDIS_PASSWORD: "${AURA_REDIS_PASSWORD}"
  JWT_SECRET: "${AURA_JWT_SECRET}"
  EHR_ENCRYPTION_KEY_V2: "${AURA_EHR_ENCRYPTION_KEY_V2}"
